[tool.poetry]
name = "sanejs"
version = "2.0"
description = "Lookup service for known legitimate JavaScript."
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "BSD-3-Clause"

classifiers=[
    'License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)',
    'Development Status :: 3 - Alpha',
    'Environment :: Console',
    'Operating System :: POSIX :: Linux',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Telecommunications Industry',
    'Intended Audience :: Information Technology',
    'Programming Language :: Python :: 3',
    'Topic :: Security',
    'Topic :: Internet',
]

[tool.poetry.scripts]
start_website = "bin.start_website:main"
start = "bin.start:main"
run_backend = "bin.run_backend:main"
build_hashes = "bin.build_hashes:main"
shutdown = "bin.shutdown:main"
stop = "bin.stop:main"
update = "bin.update:main"

[tool.poetry.dependencies]
python = "^3.10"
gitpython = "^3.1.35"
redis = {version = "^4.6.0", extras = ["hiredis"]}
flask = "^2.3.2"
gunicorn = "^21.2.0"
flask-restx = "^1.1.0"
pysanejs = "^2.0.2"
werkzeug = "^2.3.7"


[tool.poetry.group.dev.dependencies]
mypy = "^1.5.1"
types-redis = "^4.6.0.4"
ipython = "^8.14.0"

[build-system]
requires = ["poetry_core>=1.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
