[tool.poetry]
name = "sanejs"
version = "1.0"
description = "Lookup service for known legitimate JavaScript."
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "BSD-3-Clause"

classifiers=[
    'License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)',
    'Development Status :: 3 - Alpha',
    'Environment :: Console',
    'Operating System :: POSIX :: Linux',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Telecommunications Industry',
    'Intended Audience :: Information Technology',
    'Programming Language :: Python :: 3',
    'Topic :: Security',
    'Topic :: Internet',
]

[tool.poetry.scripts]
start_website = "bin.start_website:main"
start = "bin.start:main"
run_backend = "bin.run_backend:main"
build_hashes = "bin.build_hashes:main"
shutdown = "bin.shutdown:main"
stop = "bin.stop:main"

[tool.poetry.dependencies]
python = "^3.8"
gitpython = "^3.1.18"
redis = "^3.5.3"
flask = "^2.0.1"
gunicorn = {extras = ["gevent"], version = "^20.1.0"}
pysanejs = {path = "client"}

[tool.poetry.dev-dependencies]
mypy = "^0.910"
types-redis = "^3.5.6"

[build-system]
requires = ["poetry_core>=1.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
