[tool.poetry]
name = "sanejs"
version = "2.0"
description = "Lookup service for known legitimate JavaScript."
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "BSD-3-Clause"

classifiers=[
    'License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)',
    'Development Status :: 3 - Alpha',
    'Environment :: Console',
    'Operating System :: POSIX :: Linux',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Telecommunications Industry',
    'Intended Audience :: Information Technology',
    'Programming Language :: Python :: 3',
    'Topic :: Security',
    'Topic :: Internet',
]

[tool.poetry.scripts]
start_website = "bin.start_website:main"
start = "bin.start:main"
run_backend = "bin.run_backend:main"
build_hashes = "bin.build_hashes:main"
shutdown = "bin.shutdown:main"
stop = "bin.stop:main"

[tool.poetry.dependencies]
python = "^3.8"
gitpython = "^3.1.24"
redis = "^4.0.2"
flask = "^2.0.2"
gunicorn = "^20.1.0"
flask-restx = "^0.5.1"
hiredis = "^2.0.0"
pysanejs = "^2.0"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
types-redis = "^4.0"
types-setuptools = "^57.4.4"

[build-system]
requires = ["poetry_core>=1.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
